---
title: "T SQL examples"
author: "Andrea Brice"
date: "Monday, May 25, 2015"
output: html_document
---

I primarily used T-SQL to join multiple databases together as dblink authority was restricted based upon database - to - database connections.  My workgroup, as a national core reporting organization, had access to multiple dbs which might have granted access to each other.  We used our development server to cross the platforms in prep to send the final t-sql code to the reporting group.

Originally, I was using stored procedures not just to pull data from one production database into the development server, but also creating & updating interim views or tables within that same stored procedure.  I changed this direction when I realized that [documenting the code](https://github.com/andrea345/Portfolio/blob/master/Documenting_Metric_Code.RMD) in the stored procedures was more difficult "to reach," than simply pulling the data into Views.  SQL Server system tables "documented" the view code the same way Oracle databases did.  So, I moved any code or logic which was something other than a direct call to a view in another database to SQL Server Views to ensure I could capture all logic and code which "changed" anything.

By using "OpenQuery" syntax, I was able to manage some more complex query structure in my "higher" end databases - things like an ErlangB package / calculator.  However, one of the big problems I ran into with OpenQuery is the 8,000 character limit.  So, even while I was trying to migrate some of my more complex code into the MS SQL Server database, I ended up having to rewrite huge chunks of logic and break apart views I'd written in Oracle which exceeded 8,000 characters.  

This forced me to change my logic about what I should and how I should bring in data to the development server.  It also forced me into a small amount of database administration.  

As we were **not** running SQL Server 2012, all I can say is that - yet again - I found myself constrained by why I could do with this alternate variant of query language.  Again, much of the structure is quite, quite familiar, but then again, "they" just had to go and make minor changes / tweaks to things like date handling.  Substringing was also much, much more difficult in T-SQL, so I preferred to keep all my parsing & concatenating in the Oracle databases.  Really, I just wanted to use the T-SQL to join between databases because its restricted syntax was painful.  

```{sql}
	
with 
alldat as (select * FROM dbo.D_600_TRAFF where NAME like '%AN%')
,PORTCT as (
select DATETIME, ER600, MGCF,
		case when operate_status = 'up' then count(port) else 0 end as working_PORT_CT,
		case when operate_status <> 'up' then COUNT(PORT) else 0 end as non_op_PORT_CT
FROM alldat
group by DATETIME, ER600, MGCF, operate_status
		) SELECT * FROM LVL1
,TRAFF as (
    SELECT  
			
			ReportWeekStart,
			ReportWeekEnd,
			ReportMonth,
			DOW, 
			Region, 
			Market,
			DATETIME, 
			MGCF, SWITCH, MGCF_TYPE,SWITCH_VERSION,
			COUNT(port) as total_PORTS,
			ROUND(SUM(cast(Ne_Oate_Speed as FLOAT))/1000,0) as SUMMED_SPEED_BPS, 
			sum(IN_OCTETS) as IN_OCTETS, 
			sum(OUT_OCTETS) as OUT_OCTETS,
			sum(IN_OCTETS)+sum(OUT_OCTETS) AS TOTAL_OCTETS,
			sum(IN_MBPS) as IN_MBPS,
			sum(OUT_MBPS) OUT_MBPS,
			sum(IN_MBPS)+sum(OUT_MBPS) AS TOT_MBPS,
			case when sum(IN_MBPS) >= sum(OUT_MBPS) then sum(IN_MBPS)
					else sum(OUT_MBPS) end as MAX_MBPS
		FROM alldat 
		group by DATETIME, DOW, MGCF, MGCF_TYPE,SWITCH_VERSION, SWITCH,
			ReportWeekStart, ReportWeekEnd, ReportMonth, Region, Market
			)
			
,CALCD AS (
	select 
		ReportWeekStart,ReportWeekEnd,ReportMonth,DOW, a.DATETIME, Region, Market, 
			MGCF, SWITCH, MGCF_TYPE,SWITCH_VERSION,
			b.working_PORT_CT,
			b.non_op_PORT_CT,
			TOTAL_PORTS,
			SUMMED_SPEED_MBPS, 
			IN_OCTETS, 
			OUT_OCTETS,
			TOTAL_OCTETS,
			IN_MBPS,
			OUT_MBPS,
			TOT_MBPS,
			MAX_MBPS,
			ROUND(MAX_MBPS/CAST(SUMMED_SPEED_MBPS AS FLOAT),4)*100 AS LAG_UTIL

from TRAFF a, PORTCT b
where a.DATETIME = b.DATETIME	and a.ER600 = b.ER600 and 	a.SLOT = b.SLOT	
)


SELECT 				
			ReportWeekStart, 
		ReportWeekEnd, 
		ReportMonth, 
		DOW, datetime,
		Region, Market, MGCF, SWITCH, MGCF_TYPE, SWITCH_VERSION, 
		ERS8600, 
		OAM_IP, SERVER_NAME, SLOT, working_PORT_CT, non_op_PORT_CT, total_PORTS, SUMMED_SPEED_MBPS, IN_OCTETS, OUT_OCTETS, TOTAL_OCTETS, IN_MBPS, OUT_MBPS, TOT_MBPS, MAX_MBPS,
		LAG_UTIL,

CASE
	WHEN LAG_UTIL = 0  THEN 0 
	WHEN LAG_UTIL >0 AND LAG_UTIL <= 5 THEN 5   
	WHEN LAG_UTIL >5 AND LAG_UTIL <= 10 THEN 10 
	WHEN LAG_UTIL >75 AND LAG_UTIL <= 80 THEN 80 
	WHEN LAG_UTIL >80 AND LAG_UTIL <= 85 THEN 85 
	WHEN LAG_UTIL >85 AND LAG_UTIL <= 90 THEN 90 
	WHEN LAG_UTIL >90 AND LAG_UTIL <= 95 THEN 95
	ELSE 100
	END  AS UTIL_BUCKET	
			FROM CALCD

```

There are more samples, but this gives a solid example of **nesting** and **case** statements as well as the use of the **with** structure.

