Below  are some small applications I wrote using Visual Basic which pulled, parsed, and created final reports from raw data logfiles.  Most of the ETL I did captured capital equipment configuration.  

My process for collecting the data was commonly:

1.  I would write scripts in Reflections or ReflectionsX which would open a TCP/IP session to a TTY port of a node.
2.  Open a log file
3.  Execute a single MML command against the node.
4.  Close the logfile when a specific flag is detected.  Then either
  1. Open a new logfile and execute another MML command and close the new logfile OR
  2. exit the Node and move to the next node.

The logfiles were resident on a specific drive in a specific directory and then the macros were executed against specific file names from there.  


## Macro 1
The steps in this first macro
1.  Opened a new workbook, import the data in columnar format, and renamed the worksheet.  
2.  The next arranged the columns in a specific order.  
3.  Cleared flag lines.  
4.  Operated on one of the numeric fields and removed odd numbered processors if there was a "twin" condition (i.e., stand-by)
5.  Removed double blank rows.
6.  Renamed the file per instruction.


```{vb}
'Begin procedures

Sub EXEMP()
  
  'set up variables
        
 Dim resultCell As Boolean
    
  'macro to open a new workbook, import the EXEMP data, rename the worksheet "EXEMP" so rest of macro will work
    import_EXEMP
    
    ' activate the primary sheet before editing data
    
    Worksheets("EXEMP").Activate
    first_line
'clear and arrange the columns in EXEMP worksheet
    
    Organize_EXEMP_sheet
  
'clear switch flags until END is found
       Worksheets("EXEMP").Activate
       Clear_sw_flag
       
' remove odd numbered RPs with twins (STC RPs do not have RP twins)
       
       rp_remove_odd_numbers
       
' get rid of double blank rows
        blank_rows

' get rid of blank rows between STCs
          blank_rows_between_STCs
              
   '********** subroutine to get a filename to save the finished WORKSHEET as*******
    get_new_filename
       
       End Sub
'
' BEGIN PROCEDURES
 
'macro to open a new workbook, import the EXEMP data, rename the data "EXEMP" so rest of macro will work

Sub import_EXEMP()

Workbooks.Add               'add new workbook
newexemp = ActiveWorkbook.Name           'dummy name for new made workbook

Message = "Open the data file with the EXEMP printout you want."             'build message box
Style = vbOKCancel
Title = "Open EXEMP:RP=ALL,EM=ALL"
Response = MsgBox(Message, Style, Title)


If Response = vbOK Then

    Application.FindFile                    'opens the application to find a file
    exempfile = ActiveWorkbook.Name         'dummy name for data file
    ActiveCell.Columns("A:H").EntireColumn.Select
        Selection.Copy
        Windows(newexemp).Activate
        Sheets("Sheet1").Select
        Selection.PasteSpecial Paste:=xlValues, Operation:=xlNone, _
               SkipBlanks:=False, Transpose:=False
    Windows(exempfile).Activate
    ActiveWindow.Close
    Windows(newexemp).Activate
     Else
              
End If
    Range("A1").Activate                    'return cursor to top of file
    Range("A1").Select
    
    Sheets("Sheet1").Name = "EXEMP"
   
End Sub
'*************************
'subroutine to get to first line of data
'***********************
Sub first_line()

Worksheets("EXEMP").Activate
Range("A1").Select
Range("A1").Activate
Set counter = ActiveCell

Do While counter <> "RP"

    Set nextcounter = counter.Offset(1, 0)
    counter.EntireRow.Select
    Selection.Delete xlUp
    
    Set counter = nextcounter
    
Loop

End Sub



' Organize_EXEMP_sheet Macro
' Macro recorded 8/4/98 by AT&T
'
'
Private Sub Organize_EXEMP_sheet()
    Range("a1").Activate
    Range("a1").Select
    ActiveCell.Rows("1:1").EntireRow.Select
    Selection.Find(What:="pp", After:=ActiveCell, LookIn:=xlValues, _
        LookAt:=xlPart, SearchOrder:=xlByColumns, SearchDirection:= _
        xlNext, MatchCase:=False).Activate
    ActiveCell.Columns("A:A").EntireColumn.Select
    Selection.Delete Shift:=xlToLeft
    ActiveCell.Rows("1:1").EntireRow.Select
    Selection.Find(What:="twin", After:=ActiveCell, LookIn:=xlValues, _
        LookAt:=xlPart, SearchOrder:=xlByColumns, SearchDirection:= _
        xlNext, MatchCase:=False).Activate
    ActiveCell.Columns("A:A").EntireColumn.Select
    Selection.Cut
    ActiveCell.Rows("1:1").EntireRow.Select
    Selection.Find(What:="rp", After:=ActiveCell, LookIn:=xlValues, _
        LookAt:=xlPart, SearchOrder:=xlByColumns, SearchDirection:= _
        xlNext, MatchCase:=False).Activate
    ActiveCell.Offset(0, 1).Columns("A:A").EntireColumn.Select
    Selection.Insert Shift:=xlToRight
    ActiveCell.Rows("1:1").EntireRow.Select
    Selection.Find(What:="em", After:=ActiveCell, LookIn:=xlValues, _
        LookAt:=xlPart, SearchOrder:=xlByColumns, SearchDirection:= _
        xlNext, MatchCase:=False).Activate
    ActiveCell.Columns("A:A").EntireColumn.Select
    Selection.Cut
    ActiveCell.Rows("1:1").EntireRow.Select
    Selection.Find(What:="twin", After:=ActiveCell, LookIn:=xlValues, _
        LookAt:=xlPart, SearchOrder:=xlByColumns, SearchDirection:= _
        xlNext, MatchCase:=False).Activate
    ActiveCell.Offset(0, 1).Columns("A:A").EntireColumn.Select
    Selection.Insert Shift:=xlToRight
End Sub

' Remove_Switch_Flag Macro
' 'move down the row
   Private Sub Clear_sw_flag()
       Set currentcell = Worksheets("EXEMP").Range("A1")
        Do While currentcell <> "END"
        Set nextcell = currentcell.Offset(1, 0)
        If currentcell = "WO" Then
            currentcell.EntireRow.Select
            Selection.Delete Shift:=xlUp
            End If
            Set currentcell = nextcell
           Loop
       End Sub
          
       
       
 'Function to remove odd numbered RPs
 Sub rp_remove_odd_numbers()

' set statements before function
Set rpCell = Worksheets("EXEMP").Range("A2")
Set twinCell = Worksheets("EXEMP").Range("b2")
Set resultCell = Worksheets("EXEMP").Range("h2")
 
' begin function of checking for odd # RPs which are not STCs
Do While rpCell <> "END"

' set "next cell" values before function

Set nextRP = rpCell.Offset(1, 0)
Set nextTwin = twinCell.Offset(1, 0)
Set nextresult = resultCell.Offset(1, 0)
    
    rc = Right(rpCell, 1)           'to check if even # or odd # need last digit of RP #
    resultCell = (twinCell = "") Or (rc = "0") Or (rc = "2") Or (rc = "4") Or (rc = "6") Or (rc = "8") ' function to verify not an STC (no RP twin) or is
                                                                                                                                                              'not an even number as well
        
        If resultCell = False Then      ' if the number is an odd #'d RP with an RP twin, then delete the row
            rpCell.EntireRow.Select
            Selection.Delete Shift:=xlUp
            End If
            Set rpCell = nextRP
            Set twinCell = nextTwin
            Set resultCell = nextresult
          Loop
 
 End Sub
  
 
 ' get rid of double blank rows
 
Private Sub blank_rows()
    Set currentcell = Worksheets("EXEMP").Range("A1")
    
        Do While currentcell <> "END"
        Set nextcell = currentcell.Offset(1, 0)
        If currentcell = "" And nextcell = "" Then
            currentcell.EntireRow.Select
            Selection.Delete Shift:=xlUp
            End If
            Set currentcell = nextcell
           Loop
End Sub


 ' get rid of blank rows between STCs
 
Private Sub blank_rows_between_STCs()

    Set currentcell = Worksheets("EXEMP").Range("A1")           ' column for RP used to check for "end" statement
    Set twinCell = Worksheets("EXEMP").Range("B1")                 'column for RP twin
   
        Do While currentcell <> "END"
        Set nextcell = currentcell.Offset(1, 0)
        Set nextTwin = twinCell.Offset(1, 0)
        Set thirdCell = nextcell.Offset(1, 0)
        Set thirdTwin = nextTwin.Offset(1, 0)
                           
        If currentcell <> "" And twinCell = "" And nextcell = "" And nextTwin = "" And thirdCell <> "" And thirdTwin = "" Then
            Set currentcell = thirdCell
            Set twinCell = thirdTwin
            nextcell.EntireRow.Select
            Selection.Delete Shift:=xlUp
            Else
           Set currentcell = nextcell
            Set twinCell = nextTwin
            End If
                       
           Loop

End Sub

'********** subroutine to get a filename to save the finished WORKSHEET as*******

Sub get_new_filename()

prompt = "Give a path and filename for where you'd like your new data stored."
Style = vbOKOnly
Response = InputBox(prompt, Style)

newfile = Response

    ActiveWorkbook.SaveAs Filename:=newfile, _
        FileFormat:=xlNormal, Password:="", WriteResPassword:="", _
        ReadOnlyRecommended:=False, CreateBackup:=False

Range("a1").Select

prompt = "DONE NOW"
Style = vbOKOnly
Response = MsgBox(prompt, Style)


End Sub

```
The following bit is an old script which would pull in raw data, tidy it, then merge it with another file.  The file is fully commented.  

```{vb}
'THIS MODULE SHEET CONTAINS THE IMPORT FILE MACROs
'and the macros to clean up the data
'1st sub:   import_mbtrac
'2nd sub:   import_exscp
'3rd sub:   clear_sw_flag_EXSCP
'4th sub:   EXSCP_SIDES
'5th sub:   clean_up_EXSCP
'6th sub:   import_mbeqp
'7th sub:   merge_mbeq
'8th sub:   clean_MBEQP
'9th sub:   clean_MBTRAC

'****************************
'module to import mbltp:dety=mbtrac for any switch

Sub import_mbtrac()

'clean up MBTRAC sheet before execute module for new data
     
    Sheets("MBTRAC").Activate
   Dim CLEARRANGE
   Dim message
   Dim style
   Dim title
   Dim response
   
   Set CLEARRANGE = Worksheets("MBTRAC").Range("A:M")
    CLEARRANGE.EntireColumn.Clear
    Sheets("MBTRAC").Activate
    Range("A1").Activate
    Range("A1").Select
    
message = "Open the MBLTP:DETY=MBTRAC file"             'build message box
    style = vbOK
    title = "Open MBLTP:DETY=MBTRAC box "
    response = MsgBox(message, style, title)

message = "Open the MBLTP:DETY=MBTRAC file by going to the directory and highlighting file to open.  You will have to make the column limits."             'build message box
style = vbOKCancel
title = "Open MBLTP:DETY=MBTRAC box "
response = MsgBox(message, style, title)


If response = vbOK Then
Dim MBTRACFILE

    Application.FindFile
    MBTRACFILE = ActiveWorkbook.Name
    ActiveCell.Columns("A:E").EntireColumn.Select
        Selection.Copy
        Windows("TRAB2 97.xls").Activate
        Sheets("MBTRAC").Select
        Selection.PasteSpecial Paste:=xlValues, operation:=xlNone, _
               skipblanks:=False, Transpose:=False
    Windows(MBTRACFILE).Activate
    ActiveWindow.Close
    Windows("TRAB2 97.xls").Activate
     Else
              
End If
    Range("A1").Activate                    'return cursor to top of file
    Range("A1").Select


End Sub


'*********************************
'module to import exscp:name=all for any switch

Sub import_exscp()
Dim CLEARRANGE
Dim message
Dim style
Dim title
Dim response
'clean up EXSCP sheet before execute module for new data
   Set CLEARRANGE = Worksheets("EXSCP").Range("A:M")
    CLEARRANGE.EntireColumn.Clear
    Sheets("EXSCP").Activate
    Range("A1").Activate
    Range("A1").Select

message = "Open the EXSCP:NAME=ALL file.  Import with 3 COLUMNS."
style = vbOKCancel
title = "Open EXSCP:NAME=ALL box "
response = MsgBox(message, style, title)

If response = vbOK Then
Application.FindFile                                                'use the application of OpenFile to set special delimiters
Dim MBTRACFILE
MBTRACFILE = ActiveWorkbook.Name
ActiveCell.Columns("A:D").EntireColumn.Select
    Selection.Copy
    Windows("TRAB2 97.xls").Activate
    Sheets("EXSCP").Select
    Selection.PasteSpecial Paste:=xlValues, operation:=xlNone, _
           skipblanks:=False, Transpose:=False
    Windows(MBTRACFILE).Activate                    'switch back to log file to close log file
    ActiveWindow.Close
    Windows("TRAB2 97.xls").Activate
End If
End Sub



'***********************************

'module to clean up EXSCP of switch flag & move down the row then get rid of all blank lines
'within the A column so "side1" & "side2" can always be correctly selected.
Sub clear_sw_flag_EXSCP()
  Worksheets("EXSCP").Activate
  Dim currentcell
  Dim nextcell
  
  
Set currentcell = Worksheets("EXSCP").Range("A1")
        Do While currentcell <> "END"
        Set nextcell = currentcell.Offset(1, 0)
        If currentcell Like "WO*" Then
               currentcell.EntireRow.Delete Shift:=xlUp
             End If
            Set currentcell = nextcell
           Loop
    
    Sheets("EXSCP").Select                         'get rid of blank lines without having to check 9,000 lines of data:  recorded macro
    Columns("A:J").Select
    Selection.AutoFilter
    Selection.AutoFilter Field:=1, Criteria1:="<>"
    Selection.SpecialCells(xlVisible).Select
    Selection.Copy
    Sheets("WORKSHEET").Select
    Range("A1").Select
    Selection.PasteSpecial Paste:=xlValues, operation:=xlNone, _
        skipblanks:=False, Transpose:=False
    Sheets("EXSCP").Select
    Application.CutCopyMode = False
    Selection.AutoFilter
    Columns("A:M").Select
    Selection.ClearContents
    Range("A1").Select
    Sheets("WORKSHEET").Select
    Columns("A:J").Select
    Selection.Copy
    Sheets("EXSCP").Select
    ActiveSheet.Paste
    Sheets("WORKSHEET").Select
    Application.CutCopyMode = False
    Selection.ClearContents
    Sheets("EXSCP").Select
    Range("A1").Select
           
           
       End Sub
       


'**************************************

' module to move SIDE1 & SIDE2 to the side of the NAME row in EXSCP
Sub EXSCP_SIDES()

    Worksheets("EXSCP").Activate
Dim nameCell
Dim side1range
Dim side2range

    Set nameCell = Worksheets("EXSCP").Range("a1")
    
    Do Until nameCell = "END"
    If nameCell = "NAME" Then
        Set side1range = nameCell.Range("A3:C4")
        Set side2range = nameCell.Range("a5:c6")
        side1range.Select
        Selection.Cut
        nameCell.Offset(0, 4).Select
        ActiveSheet.Paste
        side2range.Select
        Selection.Cut
        nameCell.Offset(0, 7).Select
        ActiveSheet.Paste
                 
         End If
         Dim nextcell
     Set nextcell = nameCell.Offset(1, 0)
        Set nameCell = nextcell
       
Loop
End Sub

'********************
' sub to remove blank lines in EXSCP

Sub clean_up_EXSCP()
     Dim currentcell
     Dim nextcell
     
     Worksheets("EXSCP").Activate
    
    Set currentcell = Worksheets("EXSCP").Range("A1")
         
        Do While currentcell <> "NAME"              'DO WHILE to check for first header of data.  If file is imported
                                                                                'with the first lines of data being something we don't want, then they are removed.
        Set nextcell = currentcell.Offset(1, 0)
         currentcell.EntireRow.Delete Shift:=xlUp
         Set currentcell = nextcell
        
        Loop
     
     
    Sheets("EXSCP").Select                         'get rid of blank lines without having to check 9,000 lines of data:  recorded macro
    Columns("A:J").Select
    Selection.AutoFilter
    Selection.AutoFilter Field:=1, Criteria1:="<>"
    Selection.SpecialCells(xlVisible).Select
    Selection.Copy
    Sheets("WORKSHEET").Select
    Range("A1").Select
    Selection.PasteSpecial Paste:=xlValues, operation:=xlNone, _
        skipblanks:=False, Transpose:=False
    Sheets("EXSCP").Select
    Application.CutCopyMode = False
    Selection.AutoFilter
    Columns("A:M").Select
    Selection.ClearContents
    Range("A1").Select
    Sheets("WORKSHEET").Select
    Columns("A:J").Select
    Selection.Copy
    Sheets("EXSCP").Select
    ActiveSheet.Paste
    Sheets("WORKSHEET").Select
    Application.CutCopyMode = False
    Selection.ClearContents
    Sheets("EXSCP").Select
    Range("A1").Select


    Range("A1:J1").Select               'get rid of all headers except the first line
    Selection.Cut
    Range("K1").Select
    ActiveSheet.Paste
    Columns("A:J").Select
    Selection.AutoFilter
    Selection.AutoFilter Field:=1, Criteria1:="NAME"
    Selection.SpecialCells(xlVisible).Select
    Selection.ClearContents
    Columns("A:J").Select
    Selection.AutoFilter
    Selection.AutoFilter Field:=1, Criteria1:="="           'Get rid of all blank lines by filtering on non-blank lines & copying
    Selection.SpecialCells(xlVisible).Select                    'to WORKSHEET sheet
    Selection.AutoFilter Field:=1, Criteria1:="<>"
    Columns("A:J").Select
    Selection.SpecialCells(xlVisible).Select
    Selection.Copy
    
    Sheets("WORKSHEET").Select
    Range("A1").Select
    Selection.PasteSpecial Paste:=xlValues, operation:=xlNone, _
        skipblanks:=False, Transpose:=False
    
    Sheets("EXSCP").Select                                  'clean up the old data out of EXSCP
    Selection.AutoFilter Field:=1
    Application.CutCopyMode = False
    Selection.AutoFilter
    Columns("A:J").Select
    Selection.ClearContents
    Range("A1").Select
    
    Sheets("WORKSHEET").Select                  'Copy the cleaned up data back to EXSCP
    Columns("A:I").Select
    Selection.Copy
    Sheets("EXSCP").Select
    Selection.PasteSpecial Paste:=xlValues, operation:=xlNone, _
        skipblanks:=False, Transpose:=False
    
    Range("K1:T1").Select                       'add the headers back into the first row
    Application.CutCopyMode = False
    Selection.Cut
    Range("A1").Select
    ActiveSheet.Paste
    Range("A1").Select
    
    Sheets("WORKSHEET").Select              'clean up WORKSHEET sheet & put cursor back to cell A1
    Columns("A:J").Select
    Selection.ClearContents
    Range("A1").Select
    
    Sheets("EXSCP").Select              'return to EXSCP file
    
    Cells.Select                                                                    'get rid of DEV= in worksheet
    Selection.Replace What:="DEV=", Replacement:="", LookAt:=xlPart, _
    SearchOrder:=xlByRows, MatchCase:=False

End Sub


'****************************
'module to import MBEQP for any switch

Sub import_mbeqp()
Dim message
Dim title
Dim style
Dim response

'clean up MBEQP sheet and WORKSHEETbefore execute module for new data
   Dim CLEARRANGE
   Sheets("WORKSHEET").Activate
   Set CLEARRANGE = Worksheets("WORKSHEET").Range("A:M")
    CLEARRANGE.EntireColumn.Clear
    
    Range("A1").Activate
    Range("A1").Select
   
   Sheets("MBEQP").Activate
   Set CLEARRANGE = Worksheets("MBEQP").Range("A:M")
    CLEARRANGE.EntireColumn.Clear
    
    Sheets("MBEQP").Activate
    Range("A1").Activate
    Range("A1").Select

'build message box to warn user to know if there are 1 or 2 files to process

message = "Check if the file dumps have separated the MBDEQs & the MBCEQs ** "
style = vbOKOnly
title = "WARNING!!! QUIT THIS PROGRAM NOW (CTL BREAK) IF YOU DON'T KNOW IF YOU'LL BE WORKING WITH TWO FILES FOR MBEQP info!"
response = MsgBox(message, style, title)

Do Until response = vbOK
Loop
       
message = "Open the MBEQP:CETY= file"             'build message box to pull file
style = vbOKCancel
title = "Open MBEQP:CETY box "
response = MsgBox(message, style, title)

If response = vbOK Then

Dim mbeq1file
    Application.FindFile
    mbeq1file = ActiveWorkbook.Name
    ActiveCell.Columns("A:E").EntireColumn.Select
        Selection.Copy
        Windows("TRAB2 97.xls").Activate
        Sheets("MBEQP").Select
            Range("A1").Activate
            Range("A1").Select
        Selection.PasteSpecial Paste:=xlValues, operation:=xlNone, _
               skipblanks:=False, Transpose:=False
    Windows(mbeq1file).Activate
    ActiveWindow.Close
    Windows("TRAB2 97.xls").Activate
End If
                            'check if MBEQP has 1 or 2 files: one for MBDEQs & one for MBCEQs
     
     message = "Is there another MBEQP file?"
     style = vbYesNo
     title = "Open 2nd MBEQP file"
     response = MsgBox(message, style, title)
     
     If response = vbYes Then            'pull 2nd MBEQP file in
Dim mbeq2file
    Application.FindFile
    mbeq2file = ActiveWorkbook.Name
    ActiveCell.Columns("A:E").EntireColumn.Select
        Selection.Copy
        Windows("TRAB2 97.xls").Activate
        Sheets("WORKSHEET").Select
        Selection.PasteSpecial Paste:=xlValues, operation:=xlNone, _
               skipblanks:=False, Transpose:=False
    Windows(mbeq2file).Activate
    ActiveWindow.Close
    Windows("TRAB2 97.xls").Activate

merge_mbeq                      ' call subroutine to merge the two files
 Else                               'get rid of blank lines and stuff which can crash the program when both MBDEQs & MBCEQs
                                        'already exist in the same file
    
    Columns("D:D").Select
    Selection.SpecialCells(xlBlanks).Select
    Selection.Value = "X"
    
    Range("D1").Select
    Range("D1").Activate
    Dim killcell
    Dim nextkill
    
    Set killcell = ActiveCell
    Set nextkill = killcell.Offset(1, 0)
    
Do While nextkill <> ""
    
    killcell.Select
    
    If killcell = "X" Then
    
    Selection.EntireRow.Select
    Selection.Delete xlUp
   End If
    Set killcell = nextkill
    Set nextkill = killcell.Offset(1, 0)
    
  Loop
    
End If
    
    Worksheets("MBEQP").Activate
    Range("A1").Select
    Range("A1").Activate   'leave import of 2nd MBEQP file into worksheet "MBEQP"
                                     'check if you actually need the 2nd MBEQP file
  
End Sub

 '*************************************
 'module to merge 2 MBEQP files together
 '*****************************
              
 Sub merge_mbeq()
    Dim copyrange As Range
    Dim BEG1
    Dim end1
    
    Worksheets("MBEQP").Activate
    Range("A1").Select
    Range("A1").Activate
    Set BEG1 = ActiveCell
    Cells.Find(What:="END", After:=ActiveCell, LookIn:=xlFormulas, _
        LookAt:=xlPart, SearchOrder:=xlByRows, SearchDirection:=xlNext _
        , MatchCase:=False).Activate

Set end1 = ActiveCell                           'find the end of the MBDEQ file - which is where the MBCEQs will be added
    
    Worksheets("WORKSHEET").Activate
    Range("A1").Select
    Range("A1").Activate                        'get 2nd MBDEQ file data
    
    Cells.Find(What:="END", After:=ActiveCell, LookIn:=xlFormulas, _
        LookAt:=xlPart, SearchOrder:=xlByRows, SearchDirection:=xlNext _
        , MatchCase:=False).Activate
        Set copyrange = ActiveCell.CurrentRegion        ' set region to copy from "END" of file to header
        copyrange.Select
        Selection.Copy
   
     Worksheets("MBEQP").Activate                   'paste selected region of MBCEQ data
        ActiveSheet.Paste
            
        Worksheets("WORKSHEET").Activate        'clear the WORKSHEET
        Columns("A:E").Select
        Selection.ClearContents
        Range("A1").Select
        Selection.Activate
            
 End Sub
 
 
 '*************************************************
 'module to clean up MBEQP file
 '**************************************
 Sub clean_MBEQP()
 Dim currentcell
 Dim nextcell
 
   Worksheets("MBEQP").Activate
Set currentcell = Worksheets("MBEQP").Range("A1")
    currentcell.Activate
            
           Do While currentcell <> "CEQ"                    'delete all cells before first header, once first header is found, keep
            Set nextcell = currentcell.Offset(1, 0)
            currentcell.EntireRow.Delete Shift:=xlUp
           Set currentcell = nextcell
           Loop
        
        Set nextcell = currentcell.Offset(1, 0)             'skip the header
        Set currentcell = nextcell
                                                                                    'create headers to count blank cells in column 'A" because "END" may
     Dim counter1
     Dim counter2
     Dim counter3
     Dim counter4
     Dim counter5
     Dim counter6
                                                                                        
                                                                                        'or may not be found in this file.
     Set counter1 = nextcell.Offset(1, 0)
     Set counter2 = nextcell.Offset(2, 0)
     Set counter3 = nextcell.Offset(3, 0)
     Set counter4 = nextcell.Offset(4, 0)
     Set counter5 = nextcell.Offset(5, 0)
     Set counter6 = nextcell.Offset(6, 0)
        
Do While nextcell <> "" Or counter1 <> "" Or counter2 <> "" Or counter3 <> "" Or counter4 <> "" Or counter5 <> "" Or counter6 <> ""
       
       Set nextcell = currentcell.Offset(1, 0)

        If currentcell Like "MBCEQ*" Or currentcell Like "MBDEQ*" Or currentcell Like "" Then      'skip all lines with relevant data
               Else
               currentcell.EntireRow.Delete Shift:=xlUp
             End If
            Set currentcell = nextcell
            Set counter1 = counter2
            Set counter2 = counter3
            Set counter3 = counter4
            Set counter4 = counter5
            Set counter5 = counter6
            Set counter6 = counter6.Offset(1, 0)
             
Loop
       
    Range("A1").Select                          'return to top of worksheet
    Range("A1").Activate
 End Sub
 
 '*********************************

' macro to clean up MBTRAC data - removes all lines except MBTRAC- & headers
'
Sub clean_MBTRAC()
    Dim currentcell
    Dim nextcell
    
    Sheets("MBTRAC").Select
    Range("A1").Select
    Range("A1").Activate
    Columns("A:A").Select
    
    Set currentcell = Worksheets("MBTRAC").Range("A1")
        
        Do While currentcell <> "DEV"              'DO WHILE to check for first header of data.  If file is imported
                                                                                'with the first lines of data being something we don't want, then they are removed.
        Set nextcell = currentcell.Offset(1, 0)
         currentcell.EntireRow.Delete Shift:=xlUp
         Set currentcell = nextcell
        
        Loop
 
    Range("A1:E1").Select                                                           'Move headers out of the way of the autofilter so they can be returned again
    Selection.Cut Destination:=Range("F1:J1")
  
  Columns("A:A").Select
    
    Set currentcell = Worksheets("MBTRAC").Range("A1")
        
        Do While Not (currentcell Like "MBTRAC*")              'DO WHILE to check for first header of data.  If file is imported
               Set nextcell = currentcell.Offset(1, 0)
                Range("A1:E1").Select
                Selection.Delete Shift:=xlUp                                  'if the first lines of data being something we don't want, then they are removed.
                Set currentcell = nextcell
           
           Loop
    
    Columns("A:E").Select                                                   'module to filter on MBTRAC text on line.  Kill all other lines
    Selection.AutoFilter
    Selection.AutoFilter Field:=1, Criteria1:="MBTRAC*", Operator:= _
        xlAnd
    Selection.SpecialCells(xlVisible).Select
    Selection.Copy                                                          'copy the filtered MBTRAC data to the WORKSHEET sheet to clear the MBTRAC sheet
    
    Sheets("WORKSHEET").Select
    Range("A1").Select
    Selection.PasteSpecial Paste:=xlValues, operation:=xlNone, _
        skipblanks:=False, Transpose:=False
    
    Sheets("MBTRAC").Select                                 'clear the MBTRAC sheet
    Range("A1").Select
    Application.CutCopyMode = False
    Selection.AutoFilter
    Columns("A:E").Select
    Selection.ClearContents
    Range("A1").Select
    
    Sheets("WORKSHEET").Select              'copy the filtered data back into MBTRAC sheet, leaving room for the header
    Selection.Copy
    Sheets("MBTRAC").Select
    Range("A2").Select
    Selection.PasteSpecial Paste:=xlValues, operation:=xlNone, _
        skipblanks:=False, Transpose:=False
    
    Range("F1:J1").Select                           'move the header back into cell A1
    Application.CutCopyMode = False
    Selection.Cut Destination:=Range("A1:E1")
    Range("A1").Select
    
    Sheets("WORKSHEET").Select              'clear garbage data from worksheet
    Columns("A:M").Select
    Selection.ClearContents
    Range("A1").Select
    
    Sheets("WORKSHEET").Select          'return to finished MBTRAC sheet
     Range("A1").Select
    
    
End Sub

```
     
